# Generated by Django 5.0.6 on 2024-07-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=4)),
                ('image', models.ImageField(upload_to='')),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
    ]
