# Generated by Django 5.0.6 on 2024-07-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_product_date_alter_product_image'),
    ]

    operations = [
    ]
