# Generated by Django 5.0.6 on 2024-07-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_product_date'),
    ]

    operations = [
    ]
