# Generated by Django 5.0.6 on 2024-08-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_product_image_alter_product_price_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosenproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chosenproduct',
            name='item',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chosenproduct',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
